### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by rsomlette** [changLiuUNSW/React-Scaffold#1]
Hello, I tried your implementation of the mentionned library in the readme, however i'm not able to start the project with a `yarn install && yarn start`. I'm currently trying to get it working hoping it was actually working at some point.

**Comment by changLiuUNSW** [comment]
I will have a try tonight to see wehehter some libraries need to be updated or not

**Comment by changLiuUNSW** [comment]
I have updated all the packages to the latest. Let me know if it works for you or not

**Comment by rsomlette** [comment]
Nice! Thank you.
I was having issue with typescript on the mainStore & the container and your example helps a lot.
